language: android
android:
  components:
    - build-tools-23.0.0
    - android-23
    - extra-android-m2repository
    - extra-google-m2repository
    
script:
  - ./gradlew test --continue
  
before_install:
  - pip install codecov
after_success:
  - codecov

